### ISSUE TITLE
Great thanks and a small issue

### ISSUE THREAD

**Issue by Aleksanaa** [matricci/ArcBreeze#3]
Guy you are great!You successfully cured my OCD!
But the issue is...the color of the title as well as the buttons is too black.Their color should be a bit lighter to match the style of the Arc theme.

**Comment by Aleksanaa** [comment]
Fixed it by myself.Just force it use Arc color scheme.

**Comment by matricci** [comment]
How you had forced it to use the Arc Color Scheme? I want to make the decoration as close as possible to the original Arc Theme. Greetings
